name: Discord Pull Request Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_AUTHOR: ${{ github.event.pull_request.user.login }}
          AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
        run: |
          # The JSON payload for the Discord message
          JSON_PAYLOAD=$(cat <<EOF
          {
            "content": "Hey @everyone, eine neue Pull Request wurde geöffnet und ist bereit um geprüft zu werdenn!",
            "embeds": [{
              "title": "${PULL_REQUEST_TITLE}",
              "url": "${PULL_REQUEST_URL}",
              "description": "Pull Request von: **${PULL_REQUEST_AUTHOR}**. Bitte einmal checken!",
              "color": 65280,
              "author": {
                "name": "${PULL_REQUEST_AUTHOR}",
                "icon_url": "${AUTHOR_ICON_URL}"
              },
              "footer": {
                "text": "Gesendet via GitHub Actions"
              },
              "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%S.000Z')"
            }]
          }
          EOF
          )

          # Send the notification using curl
          curl --fail -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK_URL"
